### ISSUE TITLE
Вопрос по ДЗ

### ISSUE THREAD

**Issue by Inga-Z** [Inga-Z/HW_UpgreatPosts#1]
Подскажите пожалуйста, как дополнить, что бы входил полноценная ссылка, как при размещение картинки img, это нужно как то прописать в строке 61
https://github.com/Inga-Z/HW_UpgreatPosts/blob/1f3c17aeb78e6681d70ae6c1ce2a549a02ad91e5/app.js#L60-L63

**Comment by coursar** [comment]
Не понял вопроса, что значит "входил полноценная ссылка"?

**Comment by Inga-Z** [comment]
Имела ввиду что бы отображались файлы разных форматов, картинка, видео или аудио. Разобралась) прошу проверить ДЗ
